# Foundation Configuration
# Drive folders, projects, APIs, and Organization Policies from this file.

folders:
  - prod
  - non-prod
  - common
  - bootstrap

projects:
  hub-net:
    folder: common
    environment: common
    apis:
      - compute.googleapis.com
      - servicenetworking.googleapis.com
      - dns.googleapis.com
  logging:
    folder: common
    environment: common
    apis:
      - logging.googleapis.com
      - bigquery.googleapis.com
      - storage.googleapis.com
  prod-host:
    folder: prod
    environment: prod
    apis:
      - compute.googleapis.com
      - container.googleapis.com
  nonprod-host:
    folder: non-prod
    environment: non-prod
    apis:
      - compute.googleapis.com
      - container.googleapis.com

org_policies:
  - constraint: constraints/iam.disableServiceAccountKeyCreation
    enforce: true
  - constraint: constraints/compute.vmExternalIpAccess
    enforce: true
    is_list: true # Boolean vs List policy handling
